// Generated by CoffeeScript 1.6.2
(function() {
  var fieldEl, formEl, gc, initMap, mapEl, mapObj, marker, markerObj, setMap;

  mapObj = null;

  marker = null;

  markerObj = null;

  mapEl = $("#J_Map");

  fieldEl = $("#J_LocationField");

  formEl = $("#J_LocationForm");

  gc = new GeoCoder(fieldEl, formEl);

  formEl.on("submit", function() {
    return false;
  });

  formEl.find("input.btn-primary").on("click", function() {
    return formEl[0].submit();
  });

  setMap = function(latitude, longitude, setCenter) {
    var latLng;

    latLng = new google.maps.LatLng(latitude, longitude);
    markerObj.setPosition(latLng);
    if (setCenter) {
      return mapObj.setCenter(latLng);
    }
  };

  initMap = function(latitude, longitude, setCenter) {
    var option, position;

    if (marker) {
      return setMap(latitude, longitude, setCenter);
    }
    position = latitude + "," + longitude;
    option = {
      center: position,
      zoom: 10
    };
    return mapEl.gmap(option).bind("init", function(e, map) {
      marker = mapEl.gmap("addMarker", {
        position: position,
        bounds: false,
        draggable: true
      }, function(_mapObj, _markerObj) {
        mapObj = _mapObj;
        return markerObj = _markerObj;
      });
      marker.dragend(function(e) {
        return gc.search(e.latLng.toString().slice(1, -1));
      });
      return marker.click(function(e) {
        return gc.search(e.latLng.toString().slice(1, -1));
      });
    });
  };

  if (formEl[0]["location[latitude]"].value && formEl[0]["location[longitude]"].value) {
    initMap(formEl[0]["location[latitude]"].value, formEl[0]["location[longitude]"].value);
  }

  $(document).on("setLocationData", function(e, data) {
    console.log(1);
    return initMap(data.latitude, data.longitude, true);
  });

}).call(this);
