// Generated by CoffeeScript 1.6.2
(function() {
  var getCookie, setCookie;

  getCookie = function(k) {
    var m;

    m = document.cookie.match('(?:^|;)\\s*' + k + '=([^;]*)');
    if (m && m[1]) {
      return decodeURIComponent(m[1]);
    } else {
      return "";
    }
  };

  setCookie = function(k, v) {
    return document.cookie = "" + k + "=" + (encodeURIComponent(v)) + ";path=/";
  };

  if (!getCookie("current_ip")) {
    return;
  }

  if (getCookie("current_ip") === getCookie("ip")) {
    return;
  }

  GeoCoder.searchByIp(function(data) {
    var k, v, _results;

    setCookie("ip", getCookie("current_ip"));
    _results = [];
    for (k in data) {
      v = data[k];
      _results.push(setCookie(k, v));
    }
    return _results;
  });

}).call(this);
